christopheradams/elixir_style_guide

- README.md
The point of having a trailing `?` is to avoid using traling `is_` (or `are_` or similar), amirite? :)
Also, I changed the example function from `string?` to `cool?` since I don't want anyone to get potentially confused since `is_binary/2` exists and does exactly that.
> Change the predicate function so that it doesn't have a trailing `is_`

- README.md
After all, this is a **style** guide! I feel like a consistent and coherent README makes a really good impression to new contributors, and maybe it even makes them happier to contribute :).
I'm willing to send also a PR with a `CONTRIBUTING.md` file so that new contributors can catch up with the style suggested in the README.
Changes (from the commit message):
- Wrapped all the lines at the 80th column
- Added some periods here and there
- Added two newlines before each `<h1>`
> Make style coherent throughout the README

- README.md
Closes #23 
I have made some assumptions about mixing multiple "single-line `def`s" and "multi-line `def`s" - that is not to mix them.
> docs: explain how separate defs

- README.md
The best practices for using `@moduledoc` for documentation have been
influenced by the elixir-lang/elixir standard libraries.
> docs: usage for @moduledoc

- README.md
Adds an example of indenting a multiline pipeline when it occurs on the right-hand side of a pattern match.
(Also a little punctuation cleanup.)
> indent multiline pipelines on the right side of an `=`

- README.md
Since an atom can be used in a `cond` a note has been provided showing
some values that can be used for this.
> docs: provide options for :else instead of true

- README.md
As just discussed in the #elixir-lang IRC channel: We should match string using the concatenator rather than binary matching.
@josevalim approves :)
> Add string matching

- README.md
I added two guidelines:
- exception names should end with a trailing `Error`
- exception messages should be lowercase with no trailing punctuation
> Add some guidelines on exceptions

- README.md
It seems bad to have a paragraph about starting pipelines with bare variables, and then violating it here.
> avoid violating start with bare variable rule

- README.md
The link just leads to the "create new page" page.
> remove link to non-exisiting project page

- README.md
It's important to keep references to other modules sorted neatly.
> Add section about use, import, alias

- README.md
I see this in most `elixir-lang/*` repositories, so I guess it makes sense to add it in the style guide :). Let me know what you think!
> Specify how to indent the do: syntax in functions

- README.md
Super small thing, know, but it was getting at me :stuck_out_tongue:.
> Add closing brace to documentation section

- README.md
I added a new section for typespecs.
The multi-line formatting of union types is inspired by the Elixir [Typespecs reference](http://elixir-lang.org/docs/stable/elixir/typespecs.html), as well as Erlang/OTP (erlang-mode for Emacs enforces this kind of indentation).
> Add basic typespec guidelines

- README.md
Update recommended casing for modules from `CamelCase` to `PascalCase`. `CamelCase` always starts with a lower case letter (fooBar) whereas `PascalCase` always begins with a capital letter (FooBar).
> Update recommended casing for modules

- README.md
This reverts commit 27c8a290b5b0404c8551060e71e9b71cade1fbb3.
There was no particular reason to have removed this link.
> Revert "Remove extraneous link to the Ruby style guide"

- CONTRIBUTING.md
- README.md
This is a big change in the Guide.
The main reason for restructuring it was that:
* there were many H1 headings, when there should be only one.
* the guide lacked a title (it was opening up with Prelude)
* the table of contents didn't cover all the headings (License, Attribution, Contributing, Spread the Word) and it was confusing how they appeared at the end of the contents of the guide.
Additionally I disabled the TOC links to the empty sections, and marked them as empty since it was confusing the empty heading followed straight away by the next heading. 
Looking forward for your opinion guys!
UPDATE: you can see the [live version here](https://github.com/eksperimental/elixir_style_guide/tree/headings#the-elixir-style-guide)
> Headings restructured

- README.md
Zero arity functions should be invoked using parentheses to distinguish them from variables. The benefits are great, as a function call is a way more complex part of a program than using a variable so I believe it's important that those calls can not be mistaken for simple variables. 
In a future version of Elixir not doing this will produce a compiler warning, so I think it's oblivious that this is also the opinion of the core team.
Source: Andrea Leopardi (@whatyouhide) on the ElixirFountain at 24:30 (I am trying to find a better source)
> use parentheses for zero arity function calls

- README.md
I'm enjoying the guide. I came across the guidance for the trailing `?` in predicate functions and I remembered that this is actually covered in the official naming conventions for elixir.
* http://elixir-lang.org/docs/master/elixir/naming-conventions#trailing-question-mark-foo
* http://elixir-lang.org/docs/master/elixir/naming-conventions#is_-prefix-is_foo
Thanks for all your hard work! :muscle: :smile:
> Aligned predicate function guidance with official elixir convention.

- README.md
These are common to good coding practices, not specific to Elixir.
I think it's better to remove them to keep the guide focused and concise.
> Remove generic advice about comments

- README.md
It seemed worthwhile to separate the `@behaviour` attribute from other module attributes. I wasn't sure where it made the most sense to put it. I settled on under the `@moduledoc` and above imports.
> Add behaviour as an ordered attribute

- README.md
Adds a new section for structs, and also addresses issues #95 and #106.
I've seen the `defstruct` put either before or after the types. I recommend putting it after for a couple reasons:
* the type for the struct is easiest to understand when placed last in the list of types, since it will likely use more basic types already defined; if it's placed last, then you can place the `defstruct` right after it.
* `defstruct` seems closer to `def` than `use` or `alias`, hence, put it lower
What does everyone think?
> Improve struct and defstruct guidelines

- CONTRIBUTING.md
- markdown.rb
I'd like to add this style document for the Markdown lint tool (markdownlint). It will help us check PR's for formatting errors, and suggest improvements.
I'll merge it if there are no objections.
We could also set up a commit hook to run the checks automatically.
> Add markdownlint file and instructions

- README.md
- markdown.rb
Minor formatting changes that obviate a few markdown linter rule exclusions.
> Markdown rules patch

- README.md
Adds a note about using `__MODULE__` for self-references.
Addresses issue #22, based on a suggestion by @obrok
> Add rule about module self-references

- README.md
When a `defstruct` spans multiple lines, the style used by most if not all libraries is to indent the additional lines so that the keys are lined up.
Addresses issue #15 
Examples:
* [Elixir](https://github.com/elixir-lang/elixir/blob/f1cc31be3cecad911f05a536be91857702c2b766/lib/elixir/lib/uri.ex#L10)
* [Ecto](https://github.com/elixir-ecto/ecto/blob/8f1b5222a760c824340e38a66dd935686c66eaf4/lib/ecto/log_entry.ex#L29)
* [Phoenix](https://github.com/phoenixframework/phoenix/blob/297f81c7154149a13f9b61f069f5cc1b43816f3d/lib/phoenix/socket.ex#L139)
> Add defstruct indentation rule

- README.md
Tries to fix the ambiguous use of "newline" in the guide.
* "blank line" means an empty line between other lines.
* "newline" (only used once) means the line break character.
> Newlines patch

- README.md
Hi Christopher,
it was suggested that I might add some ideas to this style guide of yours.
I would really like to see the following removed/replaced by something less inflamatory:
> Write self-documenting code and ignore the rest of this section. Seriously!
This might have been copy-pasted from the Ruby styleguide. In my mind - however - it has no basis in reality and transports a *bravado* typically not found in the Elixir community. 
It further gives the impression that all decent programmers are able to something called "self documenting code", which does not exist in my opinion; especially when dealing with interfaces to third party code, comments regularly become invaluable.
Since I like to ask people "Oh, won't somebody please think of the newcomers" I would like to propose a …
> Remove self-documenting claim

- README.md
Adds indentation rules for the `with` special form, styled after the docs, supported by emacs-elixir, and [informally endorsed](https://github.com/elixir-lang/emacs-elixir/pull/348#issuecomment-264713973).
* does not include "not preferred" examples. it seems clear enough without them?
* does not show (yet) how to comment above each `with` clause using parentheses
Addresses issue #101
> Add with expression indentation rules

- README.md
Add a blank line between module groups of module `use` and `import` directives, etc.
Addresses #96
> Prefer blank line between module directive groups

- README.md
We used the term `snake_case` before, so I think it would be better to call it `snake_case` as well.
> unify term

- README.md
In Elixir 1.4, the compiler will warn you when zero-arity functions are used without parentheses.
This PR adds a notice about this new behaviour to the style guide.
> Adds reference to Elixir 1.4's warnings of parentheses+zero-arity functions

- README.md
The type `t` doesn't match the default struct `%__MODULE__{name: nil, params: []}`. This adds `nil` to the possible types. An alternative would be to default `name` to an empty string.
The reason I'd like to see this extremely nitpicky issue fixed is that this has caused problems with dialyzer in several third-party libraries for me :)
> Fix @type in `naming-main-types`

- README.md
Adds comment examples and removes one rule that isn't followed by the community. See issue #133.
> Revise comments section

- README.md
This is for #60 . I made the examples as simple as I could think of and separated the examples as @eksperimental suggested.
> Add rule for blank lines after multiline assignment

- README.md
> Added avoid repeating module name rule

- README.md
The Typespecs section has a [rule for union types] that need to be split over multiple lines:
```elixir
@type long_union_type :: some_type
| another_type
| some_other_type
| a_final_type
```
[rule for union types]: https://github.com/christopheradams/elixir_style_guide#union-types
I recall basing the original rule off of a couple of sources:
1. [Typespecs documentation]
1. Erlang standard library (e.g, [code.erl])
[Typespecs documentation]: https://github.com/elixir-lang/elixir/blob/d3f1fff8a9d00ab98e8f48ff02493831ff475d61/lib/elixir/pages/Typespecs.md#basic-types
[code.erl]: https://github.com/erlang/otp/blob/1526eaead833b3bdcd3555a12e2af62c359e7868/lib/kernel/src/code.erl#L88
It would seem the style never caught on. :) The Elixir community currently prefers the separator at the end of …
> Put union type separator at end of line

- README.md
Adds some rules for Keyword lists, including omitting square brackets from a `defstruct` argument (closes #118).
The rule for `defstruct` is not strictly necessary, as it's a logical conclusion of always omitting optional square brackets in a Keyword list, but it will be harder to overlook if it has its own rule.
> Add rules for Keyword syntax

- README.md
This PR adds a link with the Spanish translation for The Elixir Style Guide.
> Add link for Spanish translation

- README.md
Happy to say we now have a full translation of Elixir Style Guide in pt_br, the native tongue of Elixir's creator José Valim :)
> Add link to Brazilian Portuguese translation

- README.md
> Create a separate formatting section

- README.md
> Add a note about using parentheses to avoid errors in IEx

- README.md
Recommend order of tested and expected values when writing ExUnti assertions.
> Make testing assertion order more strict

- README.md
In both of the current indentation examples, the left part of the clauses have the same size. 
I think this leaves room for confusion about what should be aligned, if it's the arrows (`<-`) or the start of the clause itself.
I propose to use variables of different sizes to avoid that confusion.
> Improve indentation example

- README.md
Specifies which order the `@spec` and `@doc` should be declared. Follows convention from the Elixir language source code.
> Add guideline for @spec + @doc

- README.md
The rule https://github.com/christopheradams/elixir_style_guide#predicate-macro-names-with-guards talks about "predicate macros that can be used within guards". However, Elixir 1.6 introduced `defguard` and `defguardp`, so I think the rules should be updated here as well.
I also updated the docs for valid guard expressions.
> Update macros rules

- README.md
The anchor link for the following section isn't unique:
> Use parentheses when a def has arguments, and omit them when it doesn't.
It currently points to `#parentheses` which is already used for the another section in the README, so I changed to link to `#fun-def-parentheses`
> Fix ambiguous anchor link

- README.md
This section has been removed in 005c916ab7f.
> Remove "Syntax" from table of content

- README.md
I had the same question as #193 because the examples for [pipe operator](https://github.com/christopheradams/elixir_style_guide#pipe-operator) and [avoid single pipelines](https://github.com/christopheradams/elixir_style_guide#avoid-single-pipelines) are ambiguous on the subject.
I hope this PR will clear it up for anyone in the future.
> Clarify "avoid single pipelines" in example

- README.md
By switching the order of `require` and `alias` it forces you to write the full module when requiring. This makes it more explicit which module is required.
> Switch the order of 'require' and 'alias'

- README.md
In section `parentheses-pipe-operator` there is parentheses after for one-arity function.
> Update parentheses in README
