christopheradams/elixir_style_guide

README.md

(also, fix a capitalized function call which would have likely resulted in an
error if run)

Make an example of a larger function divided into paragraphs

---

CONTRIBUTING.md

As @knewter and I mentioned in #28, here's a first version of a `CONTRIBUTING.md` file.

Add a CONTRIBUTING.md file for contribution guidelines

---

README.md

Just minor edits and fixes to `README.md`. Everything is described in the commits messages.

Tidying up

---

README.md

1. Shows an example of the typical style used for `cond` statements
2. Changes "Misc" to a "Suggested Alternatives" section... this might open up a whole big can of worms... but it's something I'd like to try.
Especially want to ping @ericmj after our conversation in #44.

Suggested alternatives & Cond Statement

---

README.md

Thanks @ericmj for clarifying this.
https://github.com/niftyn8/elixir_style_guide/issues/50

Remove unnecessary parens (fixes #50)

---

README.md

made a typo in previous PR >_>

fix typo in comment

---

README.md

https://github.com/niftyn8/elixir_style_guide/issues/65

improve wording on pipeline indention

---

README.md

hello everyone.
this is my first contribution to the guide.
These changes are mostly aesthetic.
every commit has a description of what it tries to do.
please let me know what you think

Many formatting improvements

---

README.md

I take this syntax from progdav book, position 2095(mobi)

Addin syntax for related private functions

---

README.md

links added

---

README.md

this commit addresses https://github.com/niftyn8/elixir_style_guide/issues/68

Reword NOTE

---

README.md

Hi guys.
It is a fix typo.
Thanks

Remove unnecessary "and"

---

README.md
markdown.rb

As discussed, here are all the anchors to each bullet point. I am a bit sleepy though (12am here haha) so this will need your eyes, @christopheradams . Also I was unsure how to name the anchors of some so it can be pretty long sometimes.
Let me know your thoughts and if I need to change something!

Add anchors to bullets

---

CONTRIBUTING.md
README.md

Add translations section

---

README.md

Closes #126
if you, @christopheradams, or anybody else could review the copy-writing of this.
@lexmag @whatyouhide  I don't know if you guys are OK with the description given.

Add Alternative Style Guides

---

CONTRIBUTING.md

Added some instructions for using the Project Board + the link to it

Added project board link to contributing readme

---

README.md

Add rule for multiline list bracket placement

---

README.md

Add parentheses to function calls with pipe

---

README.md

Closes #158.
May or may not hold off on merging this until Elixir 1.6 is released.

Follow new formatter style

---

README.md

Add Chinese simplified version

---

README.md

I translated The Elixir Style Guide to French.

Added French version

---

README.md

I updated the spanish version with the latest changes. Is it ok if I send my PR to this repository or should be requested to @albertoalmagro's repository?

Update spanish translation

---

README.md

Add defmodule to order of module contents

---

README.md

I've contributed to the Elixir style guide by translating its content into Thai. This translation aims to make the style guide more accessible to Thai-speaking developers, helping them to better understand and apply Elixir's best practices. Thanks.

add Thai translation
